#!/usr/bin/env python3
"""Build a combined MINA PDF from all markdown files.

Usage:
  python3 tools/build_pdf.py

Output:
  dist/MINA-Combined.pdf
"""

from __future__ import annotations

import datetime as dt
import os
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST_DIR = ROOT / "dist"
OUTPUT_PDF = DIST_DIR / "MINA-Combined.pdf"

PLAN_MD = ROOT / "plan.md"
DELIVERABLES_DIR = ROOT / "deliverables"

SPEC_VS_SIM_GLOB = "spec-vs-sim-*.md"


def _read_version_line() -> str:
    if not PLAN_MD.exists():
        return "Version unknown"
    content = PLAN_MD.read_text(encoding="utf-8")
    match = re.search(r"^Version\s+(.+)$", content, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return "Version unknown"


def _latest_spec_vs_sim() -> Path | None:
    if not DIST_DIR.exists():
        return None
    candidates = list(DIST_DIR.glob(SPEC_VS_SIM_GLOB))
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime)


def _collect_sources() -> list[Path]:
    sources = [PLAN_MD]
    if DELIVERABLES_DIR.exists():
        sources += sorted(DELIVERABLES_DIR.glob("*.md"))

    latest_report = _latest_spec_vs_sim()
    if latest_report:
        sources.append(latest_report)

    return [p for p in sources if p.exists()]


def _ensure_pandoc() -> str:
    pandoc = shutil.which("pandoc")
    if pandoc:
        return pandoc
    raise SystemExit(
        "Pandoc is required to build the PDF. Install it (e.g., `brew install pandoc`) and retry."
    )


def _pick_pdf_engine() -> str:
    candidates = [
        "xelatex",
        "pdflatex",
        "wkhtmltopdf",
        "weasyprint",
    ]
    for engine in candidates:
        if shutil.which(engine):
            return engine
    raise SystemExit(
        "No PDF engine found. Install one of: xelatex (BasicTeX), pdflatex (MacTeX), "
        "wkhtmltopdf, or weasyprint."
    )


def _build_combined_markdown(sources: list[Path]) -> str:
    version = _read_version_line()
    date_str = dt.date.today().isoformat()

    header = [
        "```{=latex}",
        "\\begin{titlepage}",
        "\\centering",
        "{\\Huge \\bfseries MINA Specification Bundle\\par}",
        "\\vspace{0.6cm}",
        "{\\Large Minimal INstruction Architecture\\par}",
        "\\vspace{1.2cm}",
        f"{{\\large Version {version}\\par}}",
        f"{{\\large Build date: {date_str}\\par}}",
        "\\vfill",
        "{\\large Design Document and Implementation Roadmap\\par}",
        "\\vspace{0.4cm}",
        "{\\small Generated by tools/build\\_pdf.py\\par}",
        "\\end{titlepage}",
        "```",
        "",
        "```{=latex}",
        "\\tableofcontents",
        "\\newpage",
        "```",
        "",
        "```{=html}",
        '<div style="text-align:center; margin: 6em 0 4em;">',
        "<h1>MINA Specification Bundle</h1>",
        "<h2>Minimal INstruction Architecture</h2>",
        f"<p><strong>Version:</strong> {version}</p>",
        f"<p><strong>Build date:</strong> {date_str}</p>",
        "<p style=\"margin-top:3em; font-size:1.1em;\">Design Document and Implementation Roadmap</p>",
        "<p style=\"color:#666;\">Generated by tools/build_pdf.py</p>",
        "</div>",
        "<div style=\"page-break-after: always;\"></div>",
        "```",
        "",
        "---",
        "",
    ]

    body: list[str] = []
    for path in sources:
        title = path.relative_to(ROOT).as_posix()
        if path.match(str(DIST_DIR / SPEC_VS_SIM_GLOB)):
            title = f"Annex: {title}"
        body.extend([f"\n\n---\n\n# {title}\n"])
        content = path.read_text(encoding="utf-8").rstrip()
        body.append(_sanitize_for_pdf(content))

    return "\n".join(header + body) + "\n"


def _sanitize_for_pdf(text: str) -> str:
    # Replace emoji not supported by default LaTeX fonts.
    return text.replace("✅", "OK")


def main() -> None:
    pandoc = _ensure_pandoc()
    sources = _collect_sources()
    if not sources:
        raise SystemExit("No markdown sources found.")

    DIST_DIR.mkdir(parents=True, exist_ok=True)

    combined_md = _build_combined_markdown(sources)
    temp_md = DIST_DIR / "MINA-Combined.md"
    temp_md.write_text(combined_md, encoding="utf-8")

    pdf_engine = _pick_pdf_engine()

    cmd = [
        pandoc,
        str(temp_md),
        "-o",
        str(OUTPUT_PDF),
        "-V",
        "geometry:margin=1in",
        "--pdf-engine",
        pdf_engine,
    ]

    subprocess.run(cmd, check=True)
    print(f"Wrote {OUTPUT_PDF}")


if __name__ == "__main__":
    main()
